title                   : "Alfatta Rezqa"
description             : "Programmer muda yang terbiasa dengan bahasa pemrograman PHP dan Python. Pengguna linux Manjaro."
url                     : "http://alfattarezqa.com"

permalink : "/blog/:year-:month-:title.html"

author:
  image                 : "/assets/img/avatar.jpeg"
  name                  : "Alfatta Rezqa"

icon:
  favicon               : "/favicon.ico"
  apple57               : "/assets/img/apple-icon-57x57-precomposed.png"
  apple72               : "/assets/img/apple-icon-72x72-precomposed.png"
  apple114              : "/assets/img/apple-icon-114x114-precomposed.png"
  apple144              : "/assets/img/apple-icon-144x144-precomposed.png"

social:
  facebook              : "alfattarezqa"
  twitter               : "alfattarezqa"
  instagram             : "alfattarezqa"
  github                : "alfatta"
  linkedin              : "alfattarezqa"
  mail                  : "arwinnersyah@gmail.com"

timezone                : "Asia/Jakarta"

defaults:
  - values:
      layout            : "default"
      excerpt_separator : "<!--more-->"

plugins:
  - jekyll-sitemap

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []
